apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-12-03T22:32:40Z"
  labels:
    run: dacae-co
  name: dacae-co
  namespace: default
  resourceVersion: "20502"
  selfLink: /api/v1/namespaces/default/services/dacae-co
  uid: d0b8a35b-161c-11ea-b33a-42010a8001b7
spec:
  clusterIP: 10.0.12.115
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30564
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: dacae-co
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 35.239.223.114